### PR TITLE
Support FPGA CI Test Shield

### PR DESCRIPTION
**Pull request by fkjagodzinski**
- Bring `tools/COMPONENT_FPGA_CI_TEST_SHIELD` from mbed-os @ 6.11.
- Enable `tests/mbed_hal_fpga_ci_test_shield/gpio`.
- Enable `tests/mbed_hal_fpga_ci_test_shield/gpio_irq`.
- A couple of updates to make this all work:
    - Update CMake files.
    - Disable all the _FPGA CI Test Shield_ features related to firmware handling (e.g. firmware update) with `TESTER_USE_FW_UPDATE_FEATURE` macro. These depend on mbed-os' `FileHandle` and `Callback`.
    - Bring `DigitalInOut` class from mbed-os @ 6.11 and make it part of `tools/COMPONENT_FPGA_CI_TEST_SHIELD`.
    - Disable support for all peripherals except GPIO in `tools/COMPONENT_FPGA_CI_TEST_SHIELD/include/fpga_ci_test_shield/test_utils.h`. This should be reverted/fixed when enabling more test-shield tests.
    - Bring `tools/cxxsupport` from mbed-os @ 6.11.
    - Bring some of the sources back to build (e.g. `source/mbed_compat.c`, `source/mbed_pinmap_default.cpp`).
    - Use the custom IO greentea-client feature in test-shield tests.

### CODE REVIEW

**Comment by fkjagodzinski** [comment]
This is ready for review. There are still some bits to discuss:

- The CMake name of the FPGA CI Test Shield lib, `mbed-fpga-ci-test-shield` -- do we keep that/do we rename now/do we rename as a part of bigger overhaul?
- The dir name `tools/COMPONENT_FPGA_CI_TEST_SHIELD` looks weird in this repo; we tend to use lower case -- shall I rename this to something like `tools/fpga_ci_test_shield`?
- Is the `tools/cxxsupport` the right location for cxxsupport `mbed-core` feature?
- Can we keep `hal/source/mbed_pinmap_default.cpp` in it's current location? Should I move that to `tools/COMPONENT_FPGA_CI_TEST_SHIELD`?
- Do we change the old-school SPI master/slave names already or can this part wait for being actually used by the tests (when these get enabled)?

**Comment by MarceloSalazar** [comment]
> The CMake name of the FPGA CI Test Shield lib, mbed-fpga-ci-test-shield -- do we keep that/do we rename now/do we rename as a part of bigger overhaul?

Keep it for now- we'll handle a rename later, as it impacts many drivers/files.

> The dir name tools/COMPONENT_FPGA_CI_TEST_SHIELD looks weird in this repo; we tend to use lower case -- shall I rename this to something like tools/fpga_ci_test_shield?

Yes please.

>Is the tools/cxxsupport the right location for cxxsupport mbed-core feature?

IMO it's not the ideal place, but we need a restructure of files/folders anyway (see tools, bootstrap, hal/utils)
I'd suggest we keep this here for now. @hugueskamba feel free to chime in

> Can we keep hal/source/mbed_pinmap_default.cpp in it's current location? Should I move that to tools/COMPONENT_FPGA_CI_TEST_SHIELD?

This seems needed regardless on whether there is a FPGA CI test shield or not.
I'd suggest we rename it to `.c` as doesn't seem C++ code.

> Do we change the old-school SPI master/slave names already or shall this part wait for being actually used by the tests (when these get enabled)?

We should be able to change comments / docs as needed. However API needs to remain a bit more, so we don't break backwards compatibility. We'll address this as part of HAL API evolution.

**Comment by 0xc0170** [comment]
@fkjagodzinski  As indicated in #26 , we cleaned up the history. As result, this pull request was automatically closed by github due to different base (diverged). Please update your main branch, recreate this branch or a new one and cherry pick the commits to the updated main.

If you need any assistance, let me know, I am here to help you.

**Comment by fkjagodzinski** [comment]
@0xc0170 I rebased this branch on top of current main and force-pushed here but I can't reopen the PR. Can you do that for me?

**Comment by fkjagodzinski** [comment]
OK, I opened a new PR -- #32.

**Pull request closed without merging**
